version: 0.0
os: linux
files:
  - source: /var/www/html/scripts
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: /var/www/html/scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: /var/www/html/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /var/www/html/scripts/application_start.sh
      timeout: 300
      runas: ubuntu
